local_repository(
    name = "ex1",
    path = "../01_simple_program"
)

new_http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.8.0.tar.gz",
    strip_prefix = "googletest-release-1.8.0",
    build_file = "gtest.BUILD",
)
